In [21]:
# Collections

# list
# Its a mutable
# Its rep by []
# Its is indexed
# Its allow to duplicates the values
# Its is ordered

name = ['saravana', 'ram', 'liam', 'Vhin'];
print(name)

for x in name :
    print('Welcome ...', x)
    
# Add to list
## .append(<value>) 
## .insert(<position>, <value>)

name.append('raja')
print(name)

name.insert(0, 'arun')
print(name)

# Remove 
## .pop() //Last ele will removed 
## .remove(<value>)
## del Remove ele with index

name.pop()
print(name)

name.remove('ram')
print(name)

del name[len(name) - 1]
print(name)

# Copy
## .copy() //not mutable, its clone
## assign =

name2 = name.copy()
print(name2)

name3 = name
name.pop()

print(name3)

# Some methods
## Get the count of values
## .reverse() to reverse order
## .sort()

name.append('arun')
print(name.count('arun'))

name.reverse()
print(name)

name.sort()
print(name)

name.clear()
print(name)

['saravana', 'ram', 'liam', 'Vhin']
Welcome ... saravana
Welcome ... ram
Welcome ... liam
Welcome ... Vhin
['saravana', 'ram', 'liam', 'Vhin', 'raja']
['arun', 'saravana', 'ram', 'liam', 'Vhin', 'raja']
['arun', 'saravana', 'ram', 'liam', 'Vhin']
['arun', 'saravana', 'liam', 'Vhin']
['arun', 'saravana', 'liam']
['arun', 'saravana', 'liam']
['arun', 'saravana']
2
['arun', 'saravana', 'arun']
['arun', 'arun', 'saravana']
[]

In [28]:
# Tuple
## Its a mutable
## Its rep by ()
## Its is indexed
## Its allow to duplicates the values
## Its is ordered

# Some methods
## Get the count of values
## .count(<value>)
## delete entire list (del)

name = ('saravana', 'ram', 'liam', 'Vhin');
print(name)
print(name.count('ram'))

del name

('saravana', 'ram', 'liam', 'Vhin')
1

In [39]:
# Set

## Its a mutable
## Its is unindexed
## Its is unordered
## Its doesnt allow duplicates the values
## Its rep by {}

name = {'saravana', 'ram', 'liam', 'Vhin'};

### The order will gen as unordered 
print(name)

for x in name:
    print(x)

# Add

name.add('kumar')

print(name)

for x in name:
    print(x)
    
# Pop will remove the first ele

name.pop()
print(name)

# Remove the values in set

name.remove('ram')
print(name)

name.discard('liam')
print(name)

del name

# some math stuff

## .union(<set>)
## .intersection(<set>)

a = {1,3,5,7}
b = {2,4,6,8,9,1}

print(a.union(b))
print(a.intersection(b))
print(a.issubset(b))
print(a.issuperset(b))
print(a.update(b))
print(a)

{'ram', 'Vhin', 'saravana', 'liam'}
ram
Vhin
saravana
liam
{'Vhin', 'saravana', 'kumar', 'ram', 'liam'}
Vhin
saravana
kumar
ram
liam
{'saravana', 'kumar', 'ram', 'liam'}
{'saravana', 'kumar', 'liam'}
{'saravana', 'kumar'}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1}
False
False
None
{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [54]:
# Dictinoary 

## It's a mutable
## It's a indexed
## It's dose not allow duplicate
## It's rep by { KEY : VALUE }
## It's a ordered or unordered

d1 = {
    'name':'one',
    'age': 28,
    'sex' : 'male',
    'location' : {
        'tn' : ['chennai', 'trichy'],
        'kn' : ['mysore', 'benglore']
    }
}

print(d1)
print(d1.keys())
print(d1.values())

for x in d1 :
    print(x, d1[x])

for x,y in d1.items() :
    print(x,y)
    
# Add

d1['id'] = "123432"
print(d1)

# Remove

d1.pop('location')
print(d1)

d1.popitem()
print(d1)

del d1['name']
print(d1)

{'name': 'one', 'age': 28, 'sex': 'male', 'location': {'tn': ['chennai', 'trichy'], 'kn': ['mysore', 'benglore']}}
dict_keys(['name', 'age', 'sex', 'location'])
dict_values(['one', 28, 'male', {'tn': ['chennai', 'trichy'], 'kn': ['mysore', 'benglore']}])
name one
age 28
sex male
location {'tn': ['chennai', 'trichy'], 'kn': ['mysore', 'benglore']}
name one
age 28
sex male
location {'tn': ['chennai', 'trichy'], 'kn': ['mysore', 'benglore']}
{'name': 'one', 'age': 28, 'sex': 'male', 'location': {'tn': ['chennai', 'trichy'], 'kn': ['mysore', 'benglore']}, 'id': '123432'}
{'name': 'one', 'age': 28, 'sex': 'male', 'id': '123432'}
{'name': 'one', 'age': 28, 'sex': 'male'}
{'age': 28, 'sex': 'male'}